# Custom Language File for Launcher Customizer

[ejs.app]
title = "azpixelmon"

[ejs.landing]
mediaGitHubURL = "https://github.com/Rossssss1/azpixelmon"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/VjhzR35kEe"

[ejs.settings]
sourceGithubLink = "https://github.com/Rossssss1/azpixelmon"
supportLink = "https://github.com/Rossssss1/azpixelmon/issues"

[ejs.welcome]
welcomeHeader = "azpixelmon에 오신 것을 환영합니다!"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
